// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo.proto

package protos;

public interface createTodoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.createTodoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string description = 1;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 1;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
