// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo.proto

package protos;

public interface deleteTodoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.deleteTodoResponse)
    com.google.protobuf.MessageOrBuilder {
}
