// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo.proto

package protos;

public interface listTodosRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.listTodosRequest)
    com.google.protobuf.MessageOrBuilder {
}
