// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo.proto

package protos;

/**
 * Protobuf type {@code protos.listTodosResponse}
 */
public  final class listTodosResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.listTodosResponse)
    listTodosResponseOrBuilder {
  // Use listTodosResponse.newBuilder() to construct.
  private listTodosResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private listTodosResponse() {
    todos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private listTodosResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              todos_ = new java.util.ArrayList<protos.Todo>();
              mutable_bitField0_ |= 0x00000001;
            }
            todos_.add(
                input.readMessage(protos.Todo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        todos_ = java.util.Collections.unmodifiableList(todos_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protos.TodoOuterClass.internal_static_protos_listTodosResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protos.TodoOuterClass.internal_static_protos_listTodosResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protos.listTodosResponse.class, protos.listTodosResponse.Builder.class);
  }

  public static final int TODOS_FIELD_NUMBER = 1;
  private java.util.List<protos.Todo> todos_;
  /**
   * <code>repeated .protos.Todo todos = 1;</code>
   */
  public java.util.List<protos.Todo> getTodosList() {
    return todos_;
  }
  /**
   * <code>repeated .protos.Todo todos = 1;</code>
   */
  public java.util.List<? extends protos.TodoOrBuilder> 
      getTodosOrBuilderList() {
    return todos_;
  }
  /**
   * <code>repeated .protos.Todo todos = 1;</code>
   */
  public int getTodosCount() {
    return todos_.size();
  }
  /**
   * <code>repeated .protos.Todo todos = 1;</code>
   */
  public protos.Todo getTodos(int index) {
    return todos_.get(index);
  }
  /**
   * <code>repeated .protos.Todo todos = 1;</code>
   */
  public protos.TodoOrBuilder getTodosOrBuilder(
      int index) {
    return todos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < todos_.size(); i++) {
      output.writeMessage(1, todos_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < todos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, todos_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protos.listTodosResponse)) {
      return super.equals(obj);
    }
    protos.listTodosResponse other = (protos.listTodosResponse) obj;

    boolean result = true;
    result = result && getTodosList()
        .equals(other.getTodosList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTodosCount() > 0) {
      hash = (37 * hash) + TODOS_FIELD_NUMBER;
      hash = (53 * hash) + getTodosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protos.listTodosResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protos.listTodosResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protos.listTodosResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protos.listTodosResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protos.listTodosResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protos.listTodosResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protos.listTodosResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protos.listTodosResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protos.listTodosResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protos.listTodosResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protos.listTodosResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.listTodosResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.listTodosResponse)
      protos.listTodosResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.TodoOuterClass.internal_static_protos_listTodosResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.TodoOuterClass.internal_static_protos_listTodosResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.listTodosResponse.class, protos.listTodosResponse.Builder.class);
    }

    // Construct using protos.listTodosResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTodosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (todosBuilder_ == null) {
        todos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        todosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protos.TodoOuterClass.internal_static_protos_listTodosResponse_descriptor;
    }

    public protos.listTodosResponse getDefaultInstanceForType() {
      return protos.listTodosResponse.getDefaultInstance();
    }

    public protos.listTodosResponse build() {
      protos.listTodosResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public protos.listTodosResponse buildPartial() {
      protos.listTodosResponse result = new protos.listTodosResponse(this);
      int from_bitField0_ = bitField0_;
      if (todosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          todos_ = java.util.Collections.unmodifiableList(todos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.todos_ = todos_;
      } else {
        result.todos_ = todosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protos.listTodosResponse) {
        return mergeFrom((protos.listTodosResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protos.listTodosResponse other) {
      if (other == protos.listTodosResponse.getDefaultInstance()) return this;
      if (todosBuilder_ == null) {
        if (!other.todos_.isEmpty()) {
          if (todos_.isEmpty()) {
            todos_ = other.todos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTodosIsMutable();
            todos_.addAll(other.todos_);
          }
          onChanged();
        }
      } else {
        if (!other.todos_.isEmpty()) {
          if (todosBuilder_.isEmpty()) {
            todosBuilder_.dispose();
            todosBuilder_ = null;
            todos_ = other.todos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            todosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTodosFieldBuilder() : null;
          } else {
            todosBuilder_.addAllMessages(other.todos_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protos.listTodosResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protos.listTodosResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<protos.Todo> todos_ =
      java.util.Collections.emptyList();
    private void ensureTodosIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        todos_ = new java.util.ArrayList<protos.Todo>(todos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protos.Todo, protos.Todo.Builder, protos.TodoOrBuilder> todosBuilder_;

    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public java.util.List<protos.Todo> getTodosList() {
      if (todosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(todos_);
      } else {
        return todosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public int getTodosCount() {
      if (todosBuilder_ == null) {
        return todos_.size();
      } else {
        return todosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public protos.Todo getTodos(int index) {
      if (todosBuilder_ == null) {
        return todos_.get(index);
      } else {
        return todosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder setTodos(
        int index, protos.Todo value) {
      if (todosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTodosIsMutable();
        todos_.set(index, value);
        onChanged();
      } else {
        todosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder setTodos(
        int index, protos.Todo.Builder builderForValue) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        todos_.set(index, builderForValue.build());
        onChanged();
      } else {
        todosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder addTodos(protos.Todo value) {
      if (todosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTodosIsMutable();
        todos_.add(value);
        onChanged();
      } else {
        todosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder addTodos(
        int index, protos.Todo value) {
      if (todosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTodosIsMutable();
        todos_.add(index, value);
        onChanged();
      } else {
        todosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder addTodos(
        protos.Todo.Builder builderForValue) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        todos_.add(builderForValue.build());
        onChanged();
      } else {
        todosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder addTodos(
        int index, protos.Todo.Builder builderForValue) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        todos_.add(index, builderForValue.build());
        onChanged();
      } else {
        todosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder addAllTodos(
        java.lang.Iterable<? extends protos.Todo> values) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, todos_);
        onChanged();
      } else {
        todosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder clearTodos() {
      if (todosBuilder_ == null) {
        todos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        todosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public Builder removeTodos(int index) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        todos_.remove(index);
        onChanged();
      } else {
        todosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public protos.Todo.Builder getTodosBuilder(
        int index) {
      return getTodosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public protos.TodoOrBuilder getTodosOrBuilder(
        int index) {
      if (todosBuilder_ == null) {
        return todos_.get(index);  } else {
        return todosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public java.util.List<? extends protos.TodoOrBuilder> 
         getTodosOrBuilderList() {
      if (todosBuilder_ != null) {
        return todosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(todos_);
      }
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public protos.Todo.Builder addTodosBuilder() {
      return getTodosFieldBuilder().addBuilder(
          protos.Todo.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public protos.Todo.Builder addTodosBuilder(
        int index) {
      return getTodosFieldBuilder().addBuilder(
          index, protos.Todo.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.Todo todos = 1;</code>
     */
    public java.util.List<protos.Todo.Builder> 
         getTodosBuilderList() {
      return getTodosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protos.Todo, protos.Todo.Builder, protos.TodoOrBuilder> 
        getTodosFieldBuilder() {
      if (todosBuilder_ == null) {
        todosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protos.Todo, protos.Todo.Builder, protos.TodoOrBuilder>(
                todos_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        todos_ = null;
      }
      return todosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:protos.listTodosResponse)
  }

  // @@protoc_insertion_point(class_scope:protos.listTodosResponse)
  private static final protos.listTodosResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protos.listTodosResponse();
  }

  public static protos.listTodosResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<listTodosResponse>
      PARSER = new com.google.protobuf.AbstractParser<listTodosResponse>() {
    public listTodosResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new listTodosResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<listTodosResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<listTodosResponse> getParserForType() {
    return PARSER;
  }

  public protos.listTodosResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

