// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo.proto

package protos;

public interface TodoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.Todo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
