// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo.proto

package protos;

public final class TodoOuterClass {
  private TodoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Todo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Todo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_createTodoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_createTodoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_deleteTodoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_deleteTodoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_deleteTodoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_deleteTodoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_listTodosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_listTodosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_listTodosResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_listTodosResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntodo.proto\022\006protos\"\'\n\004Todo\022\n\n\002id\030\001 \001(\t" +
      "\022\023\n\013description\030\002 \001(\t\"(\n\021createTodoReque" +
      "st\022\023\n\013description\030\001 \001(\t\"\037\n\021deleteTodoReq" +
      "uest\022\n\n\002id\030\001 \001(\t\"\024\n\022deleteTodoResponse\"\022" +
      "\n\020listTodosRequest\"0\n\021listTodosResponse\022" +
      "\033\n\005todos\030\001 \003(\0132\014.protos.Todo2\313\001\n\013AuthSer" +
      "vice\0225\n\ncreateTodo\022\031.protos.createTodoRe" +
      "quest\032\014.protos.Todo\022C\n\ndeleteTodo\022\031.prot" +
      "os.deleteTodoRequest\032\032.protos.deleteTodo" +
      "Response\022@\n\tlistTodos\022\030.protos.listTodos",
      "Request\032\031.protos.listTodosResponseB\n\n\006pr" +
      "otosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protos_Todo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_Todo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Todo_descriptor,
        new java.lang.String[] { "Id", "Description", });
    internal_static_protos_createTodoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_createTodoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_createTodoRequest_descriptor,
        new java.lang.String[] { "Description", });
    internal_static_protos_deleteTodoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_deleteTodoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_deleteTodoRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_protos_deleteTodoResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protos_deleteTodoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_deleteTodoResponse_descriptor,
        new java.lang.String[] { });
    internal_static_protos_listTodosRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protos_listTodosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_listTodosRequest_descriptor,
        new java.lang.String[] { });
    internal_static_protos_listTodosResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protos_listTodosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_listTodosResponse_descriptor,
        new java.lang.String[] { "Todos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
